### ISSUE TITLE
Signature Mismatch: Android Integration

### ISSUE THREAD

**Issue by avneeshkumar** [cashfree/cashfree-android-sdk-v0#1]
key = "txMsg"
value = "ERROR: Signature mismatch"

All the APi keys are correct. Even the checksum returned from server is correct. can you help me solving the error?

**Comment by nafeydev** [comment]
Can you please share your signature generation script at nafey@gocashfree.com?

**Comment by avneeshkumar** [comment]
I have sent you the email on the above email id. Please revert back to me in case you need any more information.

Thanks
