### ISSUE TITLE
Firebase services won't work

### ISSUE THREAD

**Issue by bliveinhack** [cashfree/cashfree-android-sdk-v0#13]
When attach cashfree sdk . Firebase services is not linked with the project.
it seems there is some issue with manifest merge.

**Comment by nafeydev** [comment]
Any specific error logs/screenshots that you can share for this?

**Comment by bliveinhack** [comment]
didn't get any errors. but when cashfree used i got this logs.

` W/ComponentDiscovery: Application info not found.
W/ComponentDiscovery: Could not retrieve metadata, returning empty list of registrars.
D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.`

**Comment by bliveinhack** [comment]
You can check my test repo here.

https://github.com/bliveinhack/cashfree_error_test

**Comment by tushar-cashfree** [comment]
@bliveinhack Have you initialised firebase instance. 
https://stackoverflow.com/questions/40081539/default-firebaseapp-is-not-initialized

**Comment by bliveinhack** [comment]
@tushar-cashfree  Thanks for your response.

I have already tried using manual initialization but it's not working. you should try creating new project with firebase and cashfree sdk. so you'll get more idea.

looking forward to close this issue ASAP.
Thanks.

**Comment by bliveinhack** [comment]
Any update please ?

**Comment by bliveinhack** [comment]
@nafeydev @tushar-cashfree are you guys still looking into this matter or not ? just tell me if you are interested or not ?

**Comment by tushar-cashfree** [comment]
@bliveinhack you can add tools:node="merge" in your manifest file.

**Comment by bliveinhack** [comment]
Thanks.
