### ISSUE TITLE
sorry this page doesn't exist

### ISSUE THREAD

**Issue by abhi8702** [cashfree/cashfree-android-sdk-v0#15]

**Comment by abhi8702** [comment]
On test it is working fine but on Prod it is not.

**Comment by Luffy18346** [comment]
> On test it is working fine but on Prod it is not.

In my app, in testing mode, UPI Intent Payment is not opening on click. onFailure method is getting called. Do u have any idea about that??

**Comment by nafeydev** [comment]
Can you please drop a mail on techsupport@cashfree.com for this issue? It will be easier to follow up there.
