### ISSUE TITLE
Cannot proceed with the Payment

### ISSUE THREAD

**Issue by abhi9419** [cashfree/cashfree-android-sdk-v0#2]
Hello,
I was trying to implement the Android Payment Gateway Integration with the sample code in your repository. The sample app is being launched properly, but the problem is when I click on Payment Button then nothing happens. My checksum page is not getting called also. 
The last log in my console is:

_**10-31 07:52:49.155 27017-27017/com.gocashfree.cfsdk.sample.cfsdksample D/Volley: [1] DiskBasedCache.remove: Could not delete cache entry for key=https://project.dev/checksum, filename=329483267347756921**_

Nothing is getting printed on Log after this it is stuck here can you please help.

**Comment by nafeydev** [comment]
This is a volley warning, does not impact the functionality of SDK.

**Comment by Anu07** [comment]
Hi

Any solution found

**Comment by arjun-cashfree** [comment]
This is not an issue. The real reason for failure will be sent through the onActivityResult(). Please go through our docs.
Please contact our Tech support (techsupport@cashfree.com) if you need any further help with the integration.

**Comment by Anu07** [comment]
I have checked in onActivityResult. I got "Invalid token sent in request". I have just generated a fresh token from our server end. Can you please help me with that?

**Comment by arjun-cashfree** [comment]
You might have generated the token for TEST server and initiating the payment in SDK for PROD (or vice versa). As I had mentioned earlier, please contact our Tech support (techsupport@cashfree.com) if you need any further help with the integration.
