### ISSUE TITLE
Didn't find class "androidx.appcompat.app.AppCompatActivity"

### ISSUE THREAD

**Issue by rarago** [cashfree/cashfree-android-sdk-v0#24]
Hi,
Thanks for this SDK project. 

I downloaded this SDK and add to my project follow this doc url "https://docs.cashfree.com/docs/android/guide/#step-1-download-library".

But my project does not used AndroidX.  so, an error occurred :
**Didn't find class "androidx.appcompat.app.AppCompatActivity"**

Is there a version that do not use AndroidX?

Best Regards.
![image](https://user-images.githubusercontent.com/10431470/69533450-d035bf00-0fb2-11ea-81e7-4a7f0b967f2a.png)

**Comment by arjun-cashfree** [comment]
Our sample project also has the android support library version of SDK. Please change the dependency in the Gradle file and it should work.

**Comment by lydat** [comment]
> Our sample project also has the android support library version of SDK. Please change the dependency in the Gradle file and it should work.
![image](https://user-images.githubusercontent.com/36094163/107147785-da12ca80-698a-11eb-8091-52f031b70785.png)

hello,I used cashfree_pg_sdk_cordova, but it reported this error

**Comment by lydat** [comment]
> Our sample project also has the android support library version of SDK. Please change the dependency in the Gradle file and it should work.

help me
