### ISSUE TITLE
 Rejecting re-init on previously-failed class 

### ISSUE THREAD

**Issue by tj3333** [cashfree/cashfree-android-sdk-v0#32]
Rejecting re-init on previously-failed class java.lang.Class<com.gocashfree.cashfreesdk.a>: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/app/AppCompatActivity;

 at com.gocashfree.cashfreesdk.CFPaymentService com.gocashfree.cashfreesdk.CFPaymentService.getCFPaymentServiceInstance() (:-1)

Didn't find class "androidx.appcompat.app.AppCompatActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.bajaao-bxHyHIHJmHNtWjzcY4txHg==/base.apk"],nativeLibraryDirectories=[/data/app/com.bajaao-bxHyHIHJmHNtWjzcY4txHg==/lib/arm, /data/app/com.bajaao-bxHyHIHJmHNtWjzcY4txHg==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]

**Comment by arjun-cashfree** [comment]
This is most likely because of using incorrect dependency in your project. Our SDK uses androidX dependencies and your project might still be using android support library dependencies. Please migrate your project dependencies to androidX or use the android support library version of our SDK.
