### ISSUE TITLE
Can't able to proceed Step 4.

### ISSUE THREAD

**Issue by aarya1906** [cashfree/cashfree-android-sdk-v0#40]
How to proceed with Step 4?Please explain in detail.

**Comment by arjun-cashfree** [comment]
Please check our Android Docs :-
https://docs.cashfree.com/pg/android/integration-steps#step-3:-generate-token-(from-backend)

**Comment by arjun-cashfree** [comment]
If you need further assistance contact techsupport@cashfree.com. We'll be happy to help you out.

**Comment by aarya1906** [comment]
It will be more beneficial if u can share a video.

**Comment by aarya1906** [comment]
If u can make a video tutorial,it will be more beneficiary for me. Sent from Mail for Windows 10 From: arjun-cashfreeSent: Monday, May 11, 2020 11:55 AMTo: cashfree/cashfree-android-sdk-v0Cc: aarya1906; AuthorSubject: Re: [cashfree/cashfree-android-sdk-v0] Can't able to proceed Step 4. (#40) Please check our Android Docs :-https://docs.cashfree.com/pg/android/integration-steps#step-3:-generate-token-(from-backend)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by arjun-cashfree** [comment]
++Cashfree Techsupport <techsupport@cashfree.com>
