### ISSUE TITLE
onActivityResult() not calling after UPI payment e.g. GPay

### ISSUE THREAD

**Issue by Avishek1989** [cashfree/cashfree-android-sdk-v0#46]
Hi,
when I choose 'CARD' option for payment it's working good and I get the callback on Activity's onActivityResult() method.

But when I choose UPI payment e.g. GPay, at first a notification is coming from GPay for submitting the payment. After clicking on it I redirected to GPay App and after successful payment GPay App not exiting also my App's onActivityResult() not calling. So the user needs to start the App from launcher again.

**Comment by arjun-cashfree** [comment]
SDK will give a response for all the payment modes (even for failed or canceled transactions). Please contact techsupport@cashfree.com. We'll be happy to help you out.
