### ISSUE TITLE
Crash SDK 1.5.1

### ISSUE THREAD

**Issue by chunhui96** [cashfree/cashfree-android-sdk-v0#54]
java.lang.RuntimeException:Failure delivering result ResultInfo{who=null, request=0, result=0, data=null} to activity {com.cashfree.pg.ui.gpay.GooglePayActivity}: java.lang.NullPointerException: string arg == null
--
android.app.ActivityThread.deliverResults(ActivityThread.java:4621)
......
java.lang.NullPointerException:string arg == null
java.lang.String.concat(Native Method)
a.a.a.b.c.c.d.java.util.Map b(java.lang.String)(SourceFile:1)
a.a.a.d.b.void e()(SourceFile:12)
com.cashfree.pg.ui.gpay.GooglePayActivity.void onActivityResult(int,int,android.content.Intent)(SourceFile:10)
android.app.Activity.dispatchActivityResult(Activity.java:7516)
android.app.ActivityThread.deliverResults(ActivityThread.java:4617)
android.app.ActivityThread.handleSendResult(ActivityThread.java:4665)
android.app.ActivityThread.-wrap19(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loop(Looper.java:214)
android.app.ActivityThread.main(ActivityThread.java:6977)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:528)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:910)

**Comment by arjun-cashfree** [comment]
Updating to the latest version should resolve this issue. Please reach out to techsupport@cashfree.com for further help.
