### ISSUE TITLE
Intent Redirection vulnerability

### ISSUE THREAD

**Issue by jithinpattattu** [cashfree/cashfree-android-sdk-v0#59]
We received a notification mail from Google play regarding our app uses software that contains security vulnerabilities for users, and may be considered to be in violation of Malicious Behaviour policy.

As per the remediation for intent redirection vulnerability mentioned in the notification mail, we follow the steps in this https://support.google.com/faqs/answer/9267555. Hence we identified following areas that handle the external intent:

1. Cashfree payment gateway intent for processing payment and response handling. We have used cfPaymentService.doPayment() method

 Kindly support us with mentioning the exact classes or functions where the vulnerability issue occurs. Please consider as high priority.

**Comment by arjun-cashfree** [comment]
Please update the SDK. We have released a fix for this sometime back. This was happening because of google's SMS auto-read API. Reach out to techsupport@cashfree.com for further queries and we'll help you out.

**Comment by jithinpattattu** [comment]
Thank you for your valuable support, library update fix my issue.
