### ISSUE TITLE
`.DS_Store` is checked in the GitHub repo

### ISSUE THREAD

**Issue by atulgpt** [cashfree/cashfree-android-sdk-v0#76]
In the file https://github.com/cashfree/cashfree-android-sdk-v0/blob/master/.DS_Store, `.DS_Store` while this file is not required for the project to build or provide any other functionality to the project. This is the internal file used by `finder` on mac.

This should be removed as this shows shallow knowledge of `git` and lack of dedication towards maintaining the repo

**Comment by arjun-cashfree** [comment]
FYI. This is a deprecated repository.

**Comment by atulgpt** [comment]
Thanks, @arjun-cashfree for the reply. We can also archive the repo
